version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gjzi7k3vicie"
s3_prefix = "hello-world"
region = "eu-west-3"
capabilities = "CAPABILITY_IAM"
image_repositories = []
